name: twilio_programmable_chat
description: Integrate the Twilio Chat SDK with your Flutter app using this Twilio Programmable Chat Flutter plugin.
version: 0.1.0+1
homepage: https://gitlab.com/twilio-flutter/programmable-chat
repository: https://gitlab.com/twilio-flutter/programmable-chat
issue_tracker: https://gitlab.com/twilio-flutter/programmable-chat/issues

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^1.0.9

# TODO(WLFN): Remove the pendantic here and remove the override once the following issue is resolved:
# https://github.com/flutter/flutter/issues/48246
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

dependency_overrides:
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_programmable_chat
        pluginClass: TwilioProgrammableChatPlugin
      ios:
        pluginClass: TwilioProgrammableChatPlugin